### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [jjqoie/ioBroker.nctalk#3]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/jjqoie/iobroker.nctalk

- [x] [E003] Repository must have name ioBroker.adaptername, but now io"b"roker is in lowercase
- [x] [E004] No adapter name found in URL: https://raw.githubusercontent.com/jjqoie/iobroker.nctalk/main
- [x] [E020] Name of adapter in package.json must be lowercase and be equal to "iobroker.". Now is "undefined"
- [x] [E019] Invalid repository URL: https://github.com/jjqoie/ioBroker.nctalk. Expected: git+https://github.com/jjqoie/iobroker.nctalk.git
- [x] [E103] common.name in io-package.json must be equal to "". Now is nctalk
- [x] [E200] Not found on npm. Please publish
- [x] [E802] No topics found in the repository. Please go to "https://github.com/jjqoie/iobroker.nctalk", press the settings button beside the about title and add some topics.
- [x] [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Jochen Gerster <jjqoie@gmx.de>" at the end of README.md
- [x] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Jochen Gerster <jjqoie@gmx.de>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "" in latest repository
- [x] [W801] .npmignore not found

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by jjqoie** [comment]
[E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.nctalk"

1
[W171] "common.title" is deprecated in io-package.json

1
[W170] "common.keywords" should not contain "iobroker, adapter, smart home" io-package.json

2
[W156] Adapter should support admin 5 UI (jsonConfig)

3
[W400] Cannot find "nctalk" in latest repository

4
[W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
